(()=>{
'use strict';
const $=id=>document.getElementById(id);
const KEY='uxcheat.training.v1';
const HISTORY_LIMIT=100;
let storageOK=true,history=[],mode='aim',active=false;
let aim={running:false,hits:0,shots:0,times:[],start:0,end:0,shown:0,timer:null,targetTimer:null,frame:null,duration:30,difficulty:'normal',size:42};
let reaction={state:'idle',times:[],waitTimer:null,signalTimer:null,signalAt:0};
let toastTimer,previousFocus;
const labels={easy:'Крупная',normal:'Средняя',hard:'Маленькая'};
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const median=a=>{const b=[...a].sort((x,y)=>x-y),i=Math.floor(b.length/2);return b.length?(b.length%2?b[i]:(b[i-1]+b[i])/2):0;};
const ms=n=>Math.round(n)+' мс';
function validEntry(x){return x&&typeof x==='object'&&Number.isFinite(x.date)&&['aim','reaction'].includes(x.type)&&(x.type==='aim'?Number.isFinite(x.hits)&&Number.isFinite(x.shots)&&x.shots>=x.hits&&x.hits>=0&&[15,30,60].includes(x.duration)&&Object.hasOwn(labels,x.difficulty):Array.isArray(x.times)&&x.times.length===5&&x.times.every(t=>Number.isFinite(t)&&t>=0&&t<=5000));}
try{const raw=JSON.parse(localStorage.getItem(KEY)||'[]');history=Array.isArray(raw)?raw.filter(validEntry).slice(0,HISTORY_LIMIT):[];localStorage.setItem('uxcheat.storage-test','1');localStorage.removeItem('uxcheat.storage-test');}catch(e){storageOK=false;}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4000);}
function save(entry){history.unshift(entry);history=history.slice(0,HISTORY_LIMIT);try{localStorage.setItem(KEY,JSON.stringify(history));}catch(e){storageOK=false;toast('Локальное сохранение недоступно. История останется до перезагрузки.');}}
function state(text,running=false){$('session-status').textContent=text;$('session-dot').classList.toggle('inactive',!running);$('stop-session').hidden=!running;active=running;$('duration').disabled=running;$('difficulty').disabled=running;}
function metrics(a,b,c,d){$('metric1').textContent=a;$('metric2').textContent=b;$('metric3').textContent=c;$('metric4').textContent=d;}
function updateAimMetrics(){const remain=aim.running?Math.max(0,Math.ceil((aim.end-performance.now())/1000)):Number($('duration').value);metrics(remain+' с',String(aim.hits),aim.shots?Math.round(aim.hits/aim.shots*100)+'%':'—',aim.times.length?ms(mean(aim.times)):'—');}
function updateReactionMetrics(){metrics(reaction.times.length+'/5',reaction.times.length?ms(reaction.times[reaction.times.length-1]):'—',reaction.times.length?ms(Math.min(...reaction.times)):'—',reaction.times.length?ms(median(reaction.times)):'—');}
function selectMode(next){if(next===mode)return;cancelSession(false);mode=next;document.querySelectorAll('.mode-tab').forEach(tab=>{const selected=tab.dataset.mode===mode;tab.classList.toggle('active',selected);tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1;});$('aim-panel').hidden=mode!=='aim';$('reaction-panel').hidden=mode!=='reaction';$('aim-settings').hidden=mode!=='aim';$('reaction-settings').hidden=mode!=='reaction';const names=mode==='aim'?['ОСТАЛОСЬ','ПОПАДАНИЯ','ТОЧНОСТЬ','СРЕДНЕЕ НАВЕДЕНИЕ']:['ПОПЫТКИ','ПОСЛЕДНЯЯ','ЛУЧШАЯ','МЕДИАНА'];names.forEach((s,i)=>$('metric'+(i+1)+'-label').textContent=s);if(mode==='aim')updateAimMetrics();else updateReactionMetrics();state('Готов к тренировке');}
function clearAimTimers(){clearTimeout(aim.timer);clearTimeout(aim.targetTimer);cancelAnimationFrame(aim.frame);}
function clearReactionTimers(){clearTimeout(reaction.waitTimer);clearTimeout(reaction.signalTimer);}
function cancelSession(notify=true){const wasActive=active;clearAimTimers();clearReactionTimers();aim.running=false;$('target').hidden=true;$('aim-intro').hidden=false;$('aim-result').hidden=true;reaction.state='idle';reaction.times=[];reactionView('idle');state('Готов к тренировке');if(mode==='aim')updateAimMetrics();else updateReactionMetrics();if(wasActive&&notify)toast('Сессия остановлена. Незавершённые результаты не сохраняются.');}
function placeTarget(){if(!aim.running)return;if(performance.now()>=aim.end){finishAim();return;}const rect=$('aim-field').getBoundingClientRect(),pad=24,s=aim.size;const maxX=Math.max(pad,rect.width-pad-s),maxY=Math.max(45,rect.height-pad-s);const x=pad+Math.random()*(maxX-pad),y=45+Math.random()*(maxY-45);$('target').style.left=x+'px';$('target').style.top=y+'px';$('target').style.width=s+'px';$('target').style.height=s+'px';$('target').hidden=false;aim.shown=performance.now();clearTimeout(aim.targetTimer);aim.targetTimer=setTimeout(placeTarget,1500);}
function aimTick(){if(!aim.running)return;updateAimMetrics();if(performance.now()>=aim.end){finishAim();return;}aim.frame=requestAnimationFrame(aimTick);}
function startAim(){if(active)cancelSession(false);if(document.hidden)return;const duration=Number($('duration').value),difficulty=$('difficulty').value;aim={running:true,hits:0,shots:0,times:[],start:performance.now(),end:0,shown:0,timer:null,targetTimer:null,frame:null,duration,difficulty,size:{easy:60,normal:42,hard:26}[difficulty]};aim.end=aim.start+duration*1000;$('aim-intro').hidden=true;$('aim-result').hidden=true;state('Сессия идёт · попадай по целям',true);placeTarget();aim.timer=setTimeout(finishAim,duration*1000);aimTick();}
function finishAim(){if(!aim.running)return;aim.running=false;clearAimTimers();$('target').hidden=true;state('Сессия завершена');const accuracy=aim.shots?Math.round(aim.hits/aim.shots*100):0;const entry={type:'aim',date:Date.now(),duration:aim.duration,difficulty:aim.difficulty,hits:aim.hits,shots:aim.shots,accuracy,averageAim:aim.times.length?Math.round(mean(aim.times)):null,input:aim.input||'unknown'};save(entry);$('metric1').textContent='0 с';const box=$('aim-result');box.replaceChildren();const tag=document.createElement('p');tag.className='eyebrow';tag.textContent='SESSION COMPLETE';const number=document.createElement('div');number.className='result-number';number.textContent=String(aim.hits);const sub=document.createElement('small');sub.textContent=' попаданий';number.append(sub);const title=document.createElement('p');title.className='result-title';title.textContent=aim.hits?'Следующая цель — твой рекорд.':'Первая попытка — только начало.';const detail=document.createElement('p');detail.className='result-detail';detail.textContent=`Точность ${accuracy}% · ${aim.shots-aim.hits} промахов\n${labels[aim.difficulty]} цель · ${aim.duration} с`;detail.style.whiteSpace='pre-line';const actions=document.createElement('div');actions.className='result-buttons';const again=document.createElement('button');again.className='btn primary';again.textContent='Ещё сессия ↗';again.onclick=startAim;const stats=document.createElement('button');stats.className='btn secondary';stats.textContent='Моя статистика';stats.onclick=openStats;actions.append(again,stats);box.append(tag,number,title,detail,actions);box.hidden=false;}
$('aim-field').addEventListener('pointerdown',e=>{if(!aim.running||e.isPrimary===false||e.button!==0)return;e.preventDefault();if(performance.now()>=aim.end){finishAim();return;}aim.shots++;aim.input=e.pointerType||'mouse';if(e.target.closest('#target')){aim.hits++;aim.times.push(performance.now()-aim.shown);placeTarget();}updateAimMetrics();});
$('target').addEventListener('click',e=>{if(e.detail===0&&aim.running){toast('Для измерения аима используй мышь или касание.');}});
const reactionScreens={idle:['↯','Поймай момент.','Дождись зелёного сигнала и нажми.\n5 попыток. Не угадывай — реагируй.','НАЧАТЬ ТЕСТ ↗'],waiting:['···','Жди зелёного.','Не кликай раньше сигнала.',''],ready:['+','ЖМИ СЕЙЧАС!','Кликни, коснись или нажми пробел.',''],early:['×','Слишком рано.','Эта попытка не учитывается.\nСледи за сменой цвета.','ПОВТОРИТЬ ПОПЫТКУ ↗'],late:['⌁','Сигнал пропущен.','На ответ было 5 секунд.\nПопытка не учитывается.','ПОВТОРИТЬ ПОПЫТКУ ↗'],between:['✓','Чистое попадание.','','СЛЕДУЮЩАЯ ПОПЫТКА ↗'],finished:['↯','Сессия завершена.','','ПРОЙТИ ЕЩЁ РАЗ ↗']};
function reactionView(view){const data=reactionScreens[view];$('reaction-field').className='reaction-field '+view;$('reaction-symbol').textContent=data[0];$('reaction-title').textContent=data[1];$('reaction-text').textContent=data[2];$('reaction-text').style.whiteSpace='pre-line';$('reaction-cta').textContent=data[3];$('reaction-cta').hidden=!data[3];if(view==='between'){$('reaction-title').textContent=ms(reaction.times[reaction.times.length-1]);$('reaction-text').textContent=`Попытка ${reaction.times.length} из 5. Переведи взгляд в центр.`;}if(view==='finished'){$('reaction-title').textContent=ms(median(reaction.times));$('reaction-text').textContent=`Медиана · среднее ${ms(mean(reaction.times))}\nПопытки: ${reaction.times.map(x=>Math.round(x)).join(' / ')} мс`;} }
function armReaction(){if(document.hidden)return;clearReactionTimers();reaction.state='waiting';reactionView('waiting');state(`Попытка ${reaction.times.length+1}/5 · жди сигнала`,true);reaction.waitTimer=setTimeout(()=>{if(reaction.state!=='waiting')return;reaction.state='signal-pending';reactionView('ready');requestAnimationFrame(()=>{if(reaction.state!=='signal-pending')return;reaction.signalAt=performance.now();reaction.state='ready';state('Сигнал! Реагируй.',true);reaction.signalTimer=setTimeout(()=>{if(reaction.state!=='ready')return;reaction.state='late';reactionView('late');state('Сигнал пропущен · повтори попытку',true);},5000);});},1500+Math.random()*2500);}
function reactionAction(input='unknown'){if(mode!=='reaction')return;switch(reaction.state){case 'idle':case 'finished':reaction.times=[];reaction.input=input;updateReactionMetrics();armReaction();break;case 'between':case 'early':case 'late':armReaction();break;case 'waiting':clearReactionTimers();reaction.state='early';reactionView('early');state('Ранний клик · повтори попытку',true);break;case 'signal-pending':break;case 'ready':{const elapsed=performance.now()-reaction.signalAt;clearReactionTimers();if(elapsed>5000){reaction.state='late';reactionView('late');state('Сигнал пропущен · повтори попытку',true);break;}reaction.input=input;reaction.times.push(elapsed);updateReactionMetrics();if(reaction.times.length===5){reaction.state='finished';reactionView('finished');state('Тест завершён');save({type:'reaction',date:Date.now(),times:reaction.times.map(t=>Math.round(t)),median:Math.round(median(reaction.times)),average:Math.round(mean(reaction.times)),input:reaction.input});}else{reaction.state='between';reactionView('between');state(`Попытка ${reaction.times.length}/5 завершена`,true);}break;}}}
$('reaction-hit').addEventListener('pointerdown',e=>{if(e.button!==0||e.isPrimary===false)return;e.preventDefault();reactionAction(e.pointerType||'mouse');});
$('reaction-hit').addEventListener('click',e=>{if(e.detail===0)reactionAction('keyboard');});
document.addEventListener('keydown',e=>{if(e.code!=='Space'||e.repeat||mode!=='reaction'||$('stats-dialog').open)return;const tag=document.activeElement?.tagName;if(['SELECT','INPUT','TEXTAREA','SUMMARY','A'].includes(tag))return;if(tag==='BUTTON'&&document.activeElement!==$('reaction-hit'))return;const r=$('reaction-field').getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;e.preventDefault();reactionAction('keyboard');});
function openStats(){if(active)cancelSession();renderStats();previousFocus=document.activeElement;$('stats-dialog').showModal();}
function renderStats(){$('storage-note').textContent=storageOK?'Последние 100 завершённых сессий. Данные хранятся только в этом браузере.':'Локальное хранение недоступно. История сохранится только до перезагрузки.';$('total-sessions').textContent=history.length;const reactions=history.filter(x=>x.type==='reaction');$('best-reaction').textContent=reactions.length?ms(Math.min(...reactions.map(x=>median(x.times)))):'—';$('total-hits').textContent=history.filter(x=>x.type==='aim').reduce((sum,x)=>sum+x.hits,0);const list=$('history-list');list.replaceChildren();if(!history.length){const p=document.createElement('p');p.className='history-empty';p.textContent='Здесь пока пусто. Заверши тренировку — первая запись появится автоматически.';list.append(p);}for(const x of history){const row=document.createElement('article');row.className='history-item';const info=document.createElement('div'),title=document.createElement('h3'),meta=document.createElement('p'),value=document.createElement('strong');const date=new Date(x.date).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'});const device=({touch:'касание',mouse:'мышь',pen:'перо',keyboard:'клавиатура'})[x.input]||'устройство не определено';if(x.type==='aim'){title.textContent=`AIM · ${labels[x.difficulty]} цель · ${x.duration} с`;const accuracy=x.shots?Math.round(x.hits/x.shots*100):0;meta.textContent=`${date} · ${x.hits} попаданий · ${accuracy}% · ${device}`;value.textContent=x.hits+' HIT';}else{title.textContent='REACTION · 5 попыток';meta.textContent=`${date} · среднее ${ms(mean(x.times))} · ${device}`;value.textContent=ms(median(x.times));}info.append(title,meta);row.append(info,value);list.append(row);}$('export-stats').disabled=!history.length;$('clear-stats').disabled=!history.length;}
$('close-stats').addEventListener('click',()=>$('stats-dialog').close());$('stats-dialog').addEventListener('close',()=>previousFocus?.focus());$('stats-dialog').addEventListener('click',e=>{if(e.target!==$('stats-dialog'))return;const r=$('stats-dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('stats-dialog').close();});
$('export-stats').addEventListener('click',()=>{const data={app:'uxcheat.cc',version:1,exportedAt:new Date().toISOString(),sessions:history};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='uxcheat-sessions-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('clear-stats').addEventListener('click',()=>{if(!confirm('Удалить всю локальную историю тренировок? Это действие нельзя отменить.'))return;history=[];try{localStorage.removeItem(KEY);}catch(e){storageOK=false;}renderStats();toast('История удалена.');});
document.querySelectorAll('[data-open-stats]').forEach(b=>b.addEventListener('click',openStats));document.querySelectorAll('.mode-tab').forEach(tab=>{tab.addEventListener('click',()=>selectMode(tab.dataset.mode));tab.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?'aim':e.key==='End'?'reaction':mode==='aim'?'reaction':'aim';selectMode(next);$('tab-'+next).focus();});});
$('start-aim').addEventListener('click',startAim);$('stop-session').addEventListener('click',()=>cancelSession());$('duration').addEventListener('change',()=>{if(!active)updateAimMetrics();});$('difficulty').addEventListener('change',()=>{if(!active)updateAimMetrics();});
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{cancelSession(false);const preset=b.dataset.preset;selectMode(preset==='reaction'?'reaction':'aim');if(preset!=='reaction'){$('difficulty').value=preset;$('duration').value=preset==='easy'?'30':'60';updateAimMetrics();}$('trainer').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});toast(preset==='reaction'?'Тест реакции готов. Нажми на поле, чтобы начать.':'Настройки применены. Нажми «Начать сессию».');}));
$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement){await document.exitFullscreen();}else if(document.querySelector('.trainer-shell').requestFullscreen){await document.querySelector('.trainer-shell').requestFullscreen();}else toast('Этот браузер не поддерживает полноэкранный режим.');}catch(e){toast('Полноэкранный режим недоступен в этом браузере.');}});
document.addEventListener('fullscreenchange',()=>{$('fullscreen').setAttribute('aria-label',document.fullscreenElement?'Выйти из полноэкранного режима':'Развернуть тренажёр');if(aim.running)placeTarget();});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(aim.running)placeTarget();},100);});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)cancelSession();});
window.addEventListener('pagehide',()=>{if(active)cancelSession(false);});
state('Готов к тренировке');updateAimMetrics();
})();
